### ISSUE TITLE
WebContentNotFound

### ISSUE THREAD

**Issue by Joeyrstz** [armhil/easy-code-formatter-styles#13]
Hi, since i cannot find the repository of the tool itself, the tool throws an WebContentNotFound Exception:
![grafik](https://user-images.githubusercontent.com/21194558/124493323-c6db1e00-ddb5-11eb-824f-dd8e99a50816.png)

**Comment by NelsonIg** [comment]
I encounter the same problem when in word. Unfortunately, i used it for my thesis and now in the middle of writing it seems to be down.

**Comment by armhil** [comment]
Fixed this - apologies for the down time, I was on holidays when this happened and work kicked in afterwards so couldn't fix it :)
