### ISSUE TITLE
How to remove the add-in?

### ISSUE THREAD

**Issue by ganesshkumar** [armhil/easy-code-formatter-styles#15]
I wanted to try out this add-in and installed it in my Word. However, I am unable to remove this add-in.

What I have tried:
- Open File -> Options
- Select Add-in
- This add-in is not listed to be removed or disabled.

**Comment by armhil** [comment]
Hey Ganesh! I'm constantly surprised that people think this is an add-in issue. The developers don't control the install / uninstall experience on any of the sandboxed platforms, this is a platform capability. In other words, this is not an add-in relevant thing. That being said, have a look at the instructions in the uninstall section of the addin. I'm copying them for conveniency here:

![image](https://user-images.githubusercontent.com/4002936/131820556-f6d4c0a1-d03a-4fa7-b451-0b4644b44ca5.png)
![image](https://user-images.githubusercontent.com/4002936/131820611-5f5e6f97-a4c2-4c3e-b7b8-914cc1d91f61.png)
![image](https://user-images.githubusercontent.com/4002936/131820641-f5c89944-f6e4-49ea-ae1b-af9f1ac31be6.png)
![image](https://user-images.githubusercontent.com/4002936/131820683-4dba38da-9492-47f7-b6d1-a139b671c97c.png)

**Comment by armhil** [comment]
You can close this once you verify this method worked.
