### ISSUE TITLE
No connection！

### ISSUE THREAD

**Issue by jiaqidang** [armhil/easy-code-formatter-styles#24]
## No connection！Very frequently.

Actually, most of the time I have very little access to an internet connection in MacBook Air M1. Doesn't work 99% of the time, I try to use proxy and it didn't work either. jsut Loading and Loading.
![image](https://user-images.githubusercontent.com/47875102/188055675-1361d57b-c8b3-4053-a7d0-10a935922c7a.png)
But, I use it in PC pretty good!!!, and I try to debug in mac, It seems to be a problem with the server of the request or response.
![image](https://user-images.githubusercontent.com/47875102/188056393-01f80207-7f55-4cc1-a7f7-508be208c900.png)
Hope to fix it, Thanks!

**Comment by armhil** [comment]
As you can see it, that's not a URL that I own, but rather Microsoft. Looks like they are failing to redirect for some reason, I'll see if I can escalate this. Are you still experiencing similar issues?
