### ISSUE TITLE
[Feature Request] Customizable fonts and font sizes

### ISSUE THREAD

**Issue by furesoft** [armhil/easy-code-formatter-styles#7]
Can i change the Font without changing a theme?

**Comment by armhil** [comment]
@furesoft Can you give a bit more details into the feature you're looking for? Do you want to set a custom font - like Calibri to appear in the theme?

**Comment by furesoft** [comment]
i want to use Cascadia Code on all codeBlocks

**Comment by squasseK** [comment]
I would second that request. Would be great to be able to use other fonts. I could image a setting in the Easy Code Formatter Tab, where you choose the template. I think it could be agood idea to have it be independent from the chosen template.

This is more of a feature request than an issue.

Great work regardless, thank you!

**Comment by aress31** [comment]
Same here, would like to be able to set the Consolas font as default.

**Comment by armhil** [comment]
Hey @furesoft @squasseK @aress31 - this is added now. The font list is quite short, but I'm working on adding the fonts to the open-sourced styles lib / then we can continue extending it through PRs.
